##Anggota Kelompok 15:
1.  Jyesthaputri Laksita Wardhani (120)
2.  Nur Adzlina (220)

In [8]:
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 5.5 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [9]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.16.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.16.0-py3-none-any.whl (610 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 610.9/610.9 kB 11.2 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.16.0

In [10]:
import pandas as pd
df = pd.read_csv('dataset_instagram-comment-scraper.csv')
print(df.head())

      authorId  authorIsVerified  \
0  39555265659             False
1  54145815667             False
2   3231696612             False
3   7803187840             False
4      8271017             False

                                    authorProfilePic   authorUsername  \
0  https://instagram.fkhi2-2.fna.fbcdn.net/v/t51....     rrruubbyyy__
1  https://instagram.fkhi2-2.fna.fbcdn.net/v/t51....  cassie.archivee
2  https://instagram.fkhi2-2.fna.fbcdn.net/v/t51....      surya_riz10
3  https://instagram.fkhi2-3.fna.fbcdn.net/v/t51....          ng_vian
4  https://instagram.fkhi2-2.fna.fbcdn.net/v/t51....    aviantiarmand

           commentId commentType  \
0  18099739307381741        text
1  18069277697780802        text
2  18114390619832986        text
3  18094737968537846        text
4  18557643574075356        text

                                          commentUrl hashtags/0  isEdited  \
0  https://www.instagram.com/p/DdyZwLnJKas/c/1809...        NaN     False
1  https://www.instagram.com/p/DdyZwLnJKas/c/1806...        NaN     False
2  https://www.instagram.com/p/DdyZwLnJKas/c/1811...        NaN     False
3  https://www.instagram.com/p/DdyZwLnJKas/c/1809...        NaN     False
4  https://www.instagram.com/p/DdyZwLnJKas/c/1855...        NaN     False

   isGif  ...  mentions/0  parentCommentAuthor parentCommentId postShortcode  \
0  False  ...         NaN                  NaN             NaN   DdyZwLnJKas
1  False  ...         NaN                  NaN             NaN   DdyZwLnJKas
2  False  ...         NaN                  NaN             NaN   DdyZwLnJKas
3  False  ...         NaN                  NaN             NaN   DdyZwLnJKas
4  False  ...   Kebakaran                  NaN             NaN   DdyZwLnJKas

                                    postUrl  replyCount  \
0  https://www.instagram.com/p/DdyZwLnJKas/          74
1  https://www.instagram.com/p/DdyZwLnJKas/           4
2  https://www.instagram.com/p/DdyZwLnJKas/           0
3  https://www.instagram.com/p/DdyZwLnJKas/          12
4  https://www.instagram.com/p/DdyZwLnJKas/           8

                    scrapedAt   status  \
0  2026-10-02T17:07:27.099674  success
1  2026-10-02T17:07:27.099736  success
2  2026-10-02T17:07:27.099762  success
3  2026-10-02T17:07:27.099784  success
4  2026-10-02T17:07:27.099808  success

                                                text            timestamp
0  dan tidak ada yang bertanggung jawab atas karh...  2026-09-27T11:11:31
1           Hancur bgt hati liat hutan segundul itu💔  2026-09-27T10:44:36
2  Cocok ditanam SAWIT, kata mereka yang membakar...  2026-09-27T10:36:17
3              Tuhan beri keajaiban utk Indonesia ❤️  2026-09-27T10:35:54
4  Please jangan disingkat jadi “karhutla”, kita ...  2026-09-27T15:39:15

[5 rows x 23 columns]

In [212]:
import pandas as pd

df = pd.read_csv('dataset_instagram-comment-scraper.csv')

for i, row in enumerate(df['text'], 1):
    text_clean = str(row).replace('\n', ' ')
    print(f'[{i:03d}] {text_clean}')
    print('-' * 80)

[001] dan tidak ada yang bertanggung jawab atas karhutla ini 😢
--------------------------------------------------------------------------------
[002] Hancur bgt hati liat hutan segundul itu💔
--------------------------------------------------------------------------------
[003] Cocok ditanam SAWIT, kata mereka yang membakar 🔥🔥🔥🔥
--------------------------------------------------------------------------------
[004] Tuhan beri keajaiban utk Indonesia ❤️
--------------------------------------------------------------------------------
[005] Please jangan disingkat jadi “karhutla”, kita sebut saja @Kebakaran Hutan dan Lahan” supaya kegentingannya lebih terasa.
--------------------------------------------------------------------------------
[006] 🐷 : “TIDAK SEPARAH DI MEDSOS”
--------------------------------------------------------------------------------
[007] Siapa yg bilang, sudah 'NORMAL'???! 😡😡
--------------------------------------------------------------------------------
[008] Pak @prabowo ada tindakan biar masalah ini kelar gak pak?  Jujur kita mahasiswa yang berada diluar negri, liat keluarga dikalimantan rasanya sakit hati pak, belum juga soal dolar yang naik, turunnya juga gak stabil/ anjlok parah.  #savekalimantan
--------------------------------------------------------------------------------
[009] Pemerintah sedang mem-black campaign dirinya sendiri
--------------------------------------------------------------------------------
[010] terimakasih sdh bersuara❤️😢
--------------------------------------------------------------------------------
[011] izin kami juga di Papua terutama di Papua Barat juga masih diselimuti kabut asap yang tebal , tuhan semoga Indonesia cepat pulih kembali amin izin, izin yaaaaa 🙏🙏❤️
--------------------------------------------------------------------------------
[012] 😭😭😭😭😭😭😭😭😭 diberikan amanah malah menghancurkan... Dosa lah mereka yang tidak bertanggung-jawab.. Apa yang ditabur akan segera dituai
--------------------------------------------------------------------------------
[013] Banggg makasih bangettt udah mauu jadi pelopor buat nanem pohon di kalimantan 😭😭
--------------------------------------------------------------------------------
[014] Luas bnget hamparanny apakah itu nanti akan ada tanaman suwit yg tersusun rapih😢
--------------------------------------------------------------------------------
[015] Hari ini tepat 2 bulan, kami warga kalimantan tengah menghirup udara asap karhutla🥹😭 entah sampai kapan keadaan kek gini 💔
--------------------------------------------------------------------------------
[016] we arent mad enough💔
--------------------------------------------------------------------------------
[017] Terimakasih sudah berusaha..tpi berkaca dari Aceh sepertinya tak terlihat dimata para penguasa
--------------------------------------------------------------------------------
[018] Berapa hektar sudah dibakar?😢😭
--------------------------------------------------------------------------------
[019] jangan sampe jadi lahan sawit 😭😭💔
--------------------------------------------------------------------------------
[020] 💔💔💔
--------------------------------------------------------------------------------
[021] 💔💔💔😭😭😭
--------------------------------------------------------------------------------
[022] Luas banget yang hancur 😢
--------------------------------------------------------------------------------
[023] 💔💔💔
--------------------------------------------------------------------------------
[024] YaAllah luas sekali 🥹
--------------------------------------------------------------------------------
[025] Ini tuh terlalu mudah nangkep tersangkanya, cuma ya emang gak mau aja, orang temen sendiri 😂
--------------------------------------------------------------------------------
[026] It hurts 💔
--------------------------------------------------------------------------------
[027] Sehat buat bg jeremy, trmksh banyak bantuanya yang bahkan presiden dan mentri kehutanan pun tidak perduli
--------------------------------------------------------------------------------
[028] Yakali api bisa muncul sendiri, kalau api bisa muncul sendiri manusia2 purba ga akan gesek2 kayu kering dan gesek2 batu buat bikin api…
--------------------------------------------------------------------------------
[029] Sedihhh eee ya Tuhannnn😭😭😭💔💔💔💔💔
--------------------------------------------------------------------------------
[030] Suamiku mantan penduduk Kalimantan, setiap tahun selalu mengalami asap tebal dan penanganan yang sulit karena kondisi tanah gambutnya. Semoga ada solusi terbaik buat Karhutla ini, agar alam pulih kembali 💔
--------------------------------------------------------------------------------
[031] dan mereka bilang itu normal wen🥺🥺🥺🥺😭😭😭😭
--------------------------------------------------------------------------------
[032] Bayangkan pada gimana kemana dan seperti apa kondisi hewan hewan yg dl nya pada tinggal di situ 😢 ya allah
--------------------------------------------------------------------------------
[033] gaada aman amannya kak, aku di banjarmasin tiap hari apalagi pagi sama tengah malam, asapnya masih parah, aku pas posisi lagi sakit flu pilek, 3 masker pun masih keciuman saking parah bau asapnya, mana bikin mata perih dijalan🫠
--------------------------------------------------------------------------------
[034] Tinggal nunggu waktu, beberapa saat lagi bibit-bibit sawit akan bermunculan
--------------------------------------------------------------------------------
[035] separah ini😭💔
--------------------------------------------------------------------------------
[036] Udah bukan hutan…. 😭
--------------------------------------------------------------------------------
[037] Masalahnya amannya itu gak ada yang bisa di bakar lagi😭
--------------------------------------------------------------------------------
[038] Yng di pecat menku🥺😭
--------------------------------------------------------------------------------
[039] Itu tinggal ditanam palm tree untung banyak pasti kan juragan @budidefrianto13  dalihnya pemulihan lahan "hiyaaaa"
--------------------------------------------------------------------------------
[040] Kirim ke maudy tolong.
--------------------------------------------------------------------------------
[041] Cepat Pulih Kalimantan 😢😢😢💔💔
--------------------------------------------------------------------------------
[042] Mari kita posting ulang, dan posting Ig story agar yang lain mengetahui bahwa Kalimantan sedang tidak baik2 saja..🥺
--------------------------------------------------------------------------------
[043] dan ini tu terjadi di seluruh kalimantan, sekali lagi di seluruh Kalimantan 🫠
--------------------------------------------------------------------------------
[044] 😭😭😭😭
--------------------------------------------------------------------------------
[045] Thankyou owen @jerhemynemo
--------------------------------------------------------------------------------
[046] ASTAGFIRULLAH 🥺💔
--------------------------------------------------------------------------------
[047] 😭😭💔💔
--------------------------------------------------------------------------------
[048] 💔😭😟
--------------------------------------------------------------------------------
[049] Ya Allah habiss🥺
--------------------------------------------------------------------------------
[050] Pemerintah emang pengen ngilangin hutan tropis di kalimantan kayaknya
--------------------------------------------------------------------------------
[051] 😢
--------------------------------------------------------------------------------
[052] Di Batam saja kami sudah merasakan sesaknya asap. Tak terbayang bagaimana saudara-saudara kita di Kalimantan yang harus bertahan dan berjibaku di tengah pekatnya asap. 😢 Hasbunallahu wa ni'mal wakil. Ya Allah, jaga mereka, lindungi paru-paru dan kesehatan mereka, kuatkan hati mereka, dan segera turunkan pertolongan-Mu. Angkatlah asap dan musibah ini, gantikan dengan udara yang bersih dan keselamatan. 🤲🏻 Aamiin ya Rabbal ‘alamin.
--------------------------------------------------------------------------------
[053] Ini mau tag siapa biar orang luar tuntut pemerintah Indonesia? @unesco
--------------------------------------------------------------------------------
[054] Bayangin, sepedih apa azabnya pemimpin negara nanti
--------------------------------------------------------------------------------
[055] 😢🥺
--------------------------------------------------------------------------------
[056] Kawal terus, apakah ini bakal jadi LAHAN SAWIT ??? PANTAU TERUS.
--------------------------------------------------------------------------------
[057] 😭😭😭😭😭😭… butuh berapa tahun untuk menghijaukan kembali …😢😢😢😢😢😢
--------------------------------------------------------------------------------
[058] Nangis kita semua. 💔💔
--------------------------------------------------------------------------------
[059] masing2 ambil 1 hektar ya buat kalian jangn rebutan
--------------------------------------------------------------------------------
[060] Palembang makin parah bang💔
--------------------------------------------------------------------------------
[061] 💔💔💔
--------------------------------------------------------------------------------
[062] Dpt kabar temen di ponti sudah bisa lihat langit setelah 2 bulan, ternyata tmn2 di palangka masih berjuang 🥺 yg jauh, ubah energi sedihmu jadi bantuan utk para pahlawan relawan karhutla diantaranya melalui @ddkalteng .
--------------------------------------------------------------------------------
[063] 😭😭💔💔
--------------------------------------------------------------------------------
[064] 😢😢😢😢
--------------------------------------------------------------------------------
[065] Jujur emosi💔😭
--------------------------------------------------------------------------------
[066] Terima kasih sudah membantu dan menyuarakan kami di Kalimantan 😔🤍
--------------------------------------------------------------------------------
[067] 😢🥺
--------------------------------------------------------------------------------
[068] Beberapa bulan atau tahun ke depan dipantau lagi apakah ditanam sawit atau masih tumbuh hutan. Sebagai pembuktian ini kebakaran sengaja atau enggak
--------------------------------------------------------------------------------
[069] Sebagai org kalimantan, saya no comment untuk masalah udara yg kita pasti nya hirup di sluruh borneo ini, setiap ulasan kita lontarkan keseluruh jagat sosmed , tp semua meanggap itu hanya biasa saja , jd mungkin Kemanusiaan dimuka bumi ini udh tak ada harga nya untuk 1 nyawa yg hilang dari 1 detik hembusan nafasnya, kurangnya, penanganan, bantuan, dan janji pemimpin yang mengayomi dan mensejahterakan rakyatnya justru sebaliknya, jadi siapa lagi kalo bukan kita yg bergerak bersama demi membuka langit biru yang cerah, biarkanlah orang tak percaya bagaimana penderitaan disni, nanti juga mereka merasakan dampak dari hilangnya hutan yng menjadi paru2nya dunia. 🥺
--------------------------------------------------------------------------------
[070] Sedih banget liatnya 🥺
--------------------------------------------------------------------------------
[071] 💔💔😢😢
--------------------------------------------------------------------------------
[072] Ironisnya ada iklan di tv yg bangga pemerintah memperluas persawitannya, katanya warisan indonesia akan kembali dg adanya hutan sawit 😂😂
--------------------------------------------------------------------------------
[073] Nanti juga tumbuh lagi... Jadi Sawit 😂
--------------------------------------------------------------------------------
[074] 😭😭😭😭😭😭😭😭😭
--------------------------------------------------------------------------------
[075] Gilaaaa bener2 siap untuk sawit
--------------------------------------------------------------------------------
[076] Kemarin saya tracking bareng anak-anak,lalu mereka takjub bilang "Ibu,pohon itu besar dan kokoh banget. Kok bisa ya" lalu saya bilang, "coba peluk pohon itu" saat mereka peluk saya bilang,"di Kalimantan pasti pohonnya lebih besar dan lebih bagus lagi tapi sayang terbakar" 😢
--------------------------------------------------------------------------------
[077] Di sumbar juga euy @mfthftth
--------------------------------------------------------------------------------
[078] 😭😭😭
--------------------------------------------------------------------------------
[079] 💔
--------------------------------------------------------------------------------
[080] 😭😭semoga yg bertanggung jwb buat ini smua akan diberi balasan setimpal nanti di akhirat aamiiiiiiiinnnn🥺🥺🤲🏻🤲🏻
--------------------------------------------------------------------------------
[081] 😭💔
--------------------------------------------------------------------------------
[082] MUSNAHLAH KAU PRABOWO PENGOCOK
--------------------------------------------------------------------------------
[083] Asli, tiba2 pengen nangis, berasa sesak di dada nnton nih video. 😢😢😢😢
--------------------------------------------------------------------------------
[084] Kawal sampai rimbun kembali🔥
--------------------------------------------------------------------------------
[085] 😭😭😭😭😭💔💔💔💔💔
--------------------------------------------------------------------------------
[086] kita cuma bakar kayu di tungku aja asapnya lama banget ilangnya, ini hampir seluruh lapisan Kalimantan 😭😭💔
--------------------------------------------------------------------------------
[087] [GIF:1662597601863985]
--------------------------------------------------------------------------------
[088] Dan presidennya masih si gemoy, wapresnya masih kipas angin kosong
--------------------------------------------------------------------------------
[089] Tuhan tolong kalimantan.. Tolong.. 😭
--------------------------------------------------------------------------------
[090] Separah ini untuk memuaskan keserakahan ❤️‍🩹
--------------------------------------------------------------------------------
[091] Bentar lagi jadi kebun sawit .. saksi hidup 36 tahun d Kalimantan Tengah nih aku hehehe
--------------------------------------------------------------------------------
[092] bnr bnr abis yaallah💔😭
--------------------------------------------------------------------------------
[093] Bentar lagi numbuh sawit ituu
--------------------------------------------------------------------------------
[094] "tak separah yg di sosmed kok" ucap orng yg gk tinggal di sini, heh! Hirup lah itu udara kami ini,bengek lah kau,air kami kering di sini ,bergilir,lampu bergilir, udahlah air asin,hujan tak hujan.  tertitik air mata melihat hujan turun ,secercah harapan yg di kasih tuhan untuk memulihkan kembali😭
--------------------------------------------------------------------------------
[095] Malah jadi silent hill versi hutan, GWS untuk Kalimantankuuu❤️‍🩹❤️‍🩹❤️‍🩹
--------------------------------------------------------------------------------
[096] Wahh lahan siap tanam nii :)
--------------------------------------------------------------------------------
[097] Kalimantan Barat, KETAPANG masih parah banget sampai sekarang. Saking gada dpt bantuan dr pemerintah rakyat patungan sewa alat pemadam kebakaran 😔😔😔🙄
--------------------------------------------------------------------------------
[098] tara makjrengg ntah sawit atau kerukan saya akan tertawa dengan negara ini 😂, SAVEE KALIMANTANN !!
--------------------------------------------------------------------------------
[099] If this is true because of someone greed, may God protect us all.
--------------------------------------------------------------------------------
[100] Butuh bertahun-tahun buat menumbuhkan sebanyak itu dan lenyapnya sekejap 💔
--------------------------------------------------------------------------------
[101] Tinggal tanam sawit itu biasanya
--------------------------------------------------------------------------------
[102] [GIF:2590686864710388]
--------------------------------------------------------------------------------
[103] 3 sept masih tebal😷anak² sdh aktif skolah
--------------------------------------------------------------------------------
[104] kelar juga proyek pertama lanjut nyawitttttt
--------------------------------------------------------------------------------
[105] Apa kabar kami yg tinggal dipalembang😭
--------------------------------------------------------------------------------
[106] 💔💔💔💔💔💔💔💔💔
--------------------------------------------------------------------------------
[107] Kami di sumatera selatan kabupaten Ogan Ilir parah asap sampai masuk rumah mata pedih 🥺semoga membaik amin
--------------------------------------------------------------------------------
[108] 🥺🥺🥺🥺😭💔
--------------------------------------------------------------------------------
[109] 💔
--------------------------------------------------------------------------------
[110] 💔 tamaknya manusia
--------------------------------------------------------------------------------
[111] Bentar lg terbentang hijau rimbun sawit 😭😢.
--------------------------------------------------------------------------------
[112] 💔😭
--------------------------------------------------------------------------------
[113] Semoga nanti bisa pulih seperti semula 💔
--------------------------------------------------------------------------------
[114] 🥺💔
--------------------------------------------------------------------------------
[115] Siapp ditanami sawit
--------------------------------------------------------------------------------
[116] 😭😭😭
--------------------------------------------------------------------------------
[117] Trimksh owen
--------------------------------------------------------------------------------
[118] Gak kebayang pas musim hujan. YaAllah... Semoga tdk ada bencana lagi untuk saudara ku di sana.....
--------------------------------------------------------------------------------
[119] Habis ini tumbuhlah anakan sawit
--------------------------------------------------------------------------------
[120] [GIF:1405410575127333]
--------------------------------------------------------------------------------
[121] Ya Allah 💔😭😭😭
--------------------------------------------------------------------------------
[122] 💔💔💔💔😢😢😢😢😢😢😢
--------------------------------------------------------------------------------
[123] Sebentar lagi itu tumbuh bibit sawit
--------------------------------------------------------------------------------
[124] Ya ampun hutan kami.... 😭😭😭😭😭😭
--------------------------------------------------------------------------------
[125] semoga turun hujan sederas derasnya setiap hari sampai tahun depan yaaaa di kalimantan dan sekitarnyaaa 🙏🏻✨
--------------------------------------------------------------------------------
[126] Bukan Kebakaran Hutan dan Lahan tapi, PEMbakaran Hutan dan Lahan 😭😢
--------------------------------------------------------------------------------
[127] 😭💔
--------------------------------------------------------------------------------
[128] @prabowo awas aja lahan seluas ini yang kebakar berubah jadi sawit, kalau berubah jadi sawit anda wajib memberi kami yang terdampak gaji 2 digit lebih!
--------------------------------------------------------------------------------
[129] gila
--------------------------------------------------------------------------------
[130] Nangis🥺
--------------------------------------------------------------------------------
[131] rumah tetangga aja nggak keliatan 😭
--------------------------------------------------------------------------------
[132] Sudah berapa kuadriliun nyawa hilang, doaku bukan lagi menyumpahi pelaku, tapi lebih ke semoga kami bisa menyaksikan siksaan yg akan mereka rasakan
--------------------------------------------------------------------------------
[133] Satu bulan kemudian jadi lahan sawit itu
--------------------------------------------------------------------------------

In [213]:
import re
def remove_mention_hastag(text):
    text = re.sub(r'#\w+', '', text)
    text = re.sub(r'@[A-Za-z0-9_]+', '', text)
    return text

df['1_hastag_mention_removal'] = df['text'].apply(remove_mention_hastag)

print("1. Hashtag & mention removal")
display(df['1_hastag_mention_removal'].head(10))

1. Hashtag & mention removal

0    dan tidak ada yang bertanggung jawab atas karh...
1             Hancur bgt hati liat hutan segundul itu💔
2    Cocok ditanam SAWIT, kata mereka yang membakar...
3                Tuhan beri keajaiban utk Indonesia ❤️
4    Please jangan disingkat jadi “karhutla”, kita ...
5                        🐷 : “TIDAK SEPARAH DI MEDSOS”
6               Siapa yg bilang, sudah 'NORMAL'???! 😡😡
7    Pak  ada tindakan biar masalah ini kelar gak p...
8    Pemerintah sedang mem-black campaign dirinya s...
9                          terimakasih sdh bersuara❤️😢
Name: 1_hastag_mention_removal, dtype: object

In [216]:
def lower_casing(text):
    return str(text).lower()

df['2_lower'] = df['1_hastag_mention_removal'].apply(lower_casing)

print("2. Lower casing")
display(df['2_lower'].head(10))

2. Lower casing

0    dan tidak ada yang bertanggung jawab atas karh...
1             hancur bgt hati liat hutan segundul itu💔
2    cocok ditanam sawit, kata mereka yang membakar...
3                tuhan beri keajaiban utk indonesia ❤️
4    please jangan disingkat jadi “karhutla”, kita ...
5                        🐷 : “tidak separah di medsos”
6               siapa yg bilang, sudah 'normal'???! 😡😡
7    pak  ada tindakan biar masalah ini kelar gak p...
8    pemerintah sedang mem-black campaign dirinya s...
9                          terimakasih sdh bersuara❤️😢
Name: 2_lower, dtype: object

In [217]:
import emoji

def demojize_text(text):
    return emoji.demojize(str(text), delimiters=(' emoji_', ' '), language='id')

df['3_autoemoji'] = df['2_lower'].apply(demojize_text)

print("3. Removal of emoji")
display(df['3_autoemoji'].head(10))

3. Removal of emoji

0    dan tidak ada yang bertanggung jawab atas karh...
1    hancur bgt hati liat hutan segundul itu emoji_...
2    cocok ditanam sawit, kata mereka yang membakar...
3    tuhan beri keajaiban utk indonesia  emoji_hati...
4    please jangan disingkat jadi “karhutla”, kita ...
5        emoji_wajah_babi  : “tidak separah di medsos”
6    siapa yg bilang, sudah 'normal'???!  emoji_waj...
7    pak  ada tindakan biar masalah ini kelar gak p...
8    pemerintah sedang mem-black campaign dirinya s...
9    terimakasih sdh bersuara emoji_hati_merah  emo...
Name: 3_autoemoji, dtype: object

In [218]:
import re

def remove_punctuations(text):
    text = re.sub(r'[^\w\s]', ' ', str(text))
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['4_punct'] = df['3_autoemoji'].apply(remove_punctuations)

print("4. Removal of Punctuations")
display(df['4_punct'].head(10))

4. Removal of Punctuations

0    dan tidak ada yang bertanggung jawab atas karh...
1    hancur bgt hati liat hutan segundul itu emoji_...
2    cocok ditanam sawit kata mereka yang membakar ...
3    tuhan beri keajaiban utk indonesia emoji_hati_...
4    please jangan disingkat jadi karhutla kita seb...
5             emoji_wajah_babi tidak separah di medsos
6    siapa yg bilang sudah normal emoji_wajah_sanga...
7    pak ada tindakan biar masalah ini kelar gak pa...
8    pemerintah sedang mem black campaign dirinya s...
9    terimakasih sdh bersuara emoji_hati_merah emoj...
Name: 4_punct, dtype: object

In [219]:
import re

def normalize_text(text):
    text = re.sub(r'(\w)\1{2,}', r'\1', text)
    return text

df['5_normalization'] = df['4_punct'].apply(normalize_text)

print("5. Text Normalization")
display(df['5_normalization'].head(10))

5. Text Normalization

0    dan tidak ada yang bertanggung jawab atas karh...
1    hancur bgt hati liat hutan segundul itu emoji_...
2    cocok ditanam sawit kata mereka yang membakar ...
3    tuhan beri keajaiban utk indonesia emoji_hati_...
4    please jangan disingkat jadi karhutla kita seb...
5             emoji_wajah_babi tidak separah di medsos
6    siapa yg bilang sudah normal emoji_wajah_sanga...
7    pak ada tindakan biar masalah ini kelar gak pa...
8    pemerintah sedang mem black campaign dirinya s...
9    terimakasih sdh bersuara emoji_hati_merah emoj...
Name: 5_normalization, dtype: object

In [220]:
import re

def correct_spelling(text):
    typo_dict = {
        'bnget': 'banget', 'bangett': 'banget', 'banggg': 'bang', 'nnton': 'nonton', 'aja': 'saja',
        'suwit': 'sawit', 'nyawit': 'sawit', 'negri': 'negeri', 'rapih': 'rapi', 'mentri': 'menteri',
        'luasny': 'luasnya', 'hamparanny': 'hamparannya', 'bantuanya': 'bantuannya', 'jwb': 'jawab', 'jangn': 'jangan',
        'dikarenakn': 'dikarenakan', 'perduli': 'peduli', 'yng': 'yang', 'smua': 'semua', 'ujan': 'hujan',
        'sluruh': 'seluruh', 'meanggap': 'menganggap', 'tu': 'itu', 'disni': 'disini', 'president': 'presiden',
        'ilangnya': 'hilangnya', 'abis': 'habis', 'udahlah': 'sudahlah', 'skolah': 'sekolah', 'alloh': 'allah'
        }

    phrase_dict = {
        'tidak ada': 'tidakada', 'gak ada': 'tidakada', 'ga ada': 'tidakada', 'gaada': 'tidakada', 'gada': 'tidakada',
        'tidak mau': 'tidakmau', 'gak mau': 'tidakmau', 'ga mau': 'tidakmau', 'juaahat': 'jahat', 'buangeet': 'banget',
        'tidak bisa': 'tidakbisa', 'gak bisa': 'tidakbisa', 'ga bisa': 'tidakbisa', "hasbunallahu wa ni'mal wakil": "hasbunallahuwanimalwakil",
        'tidak peduli': 'tidakpeduli', 'gak perduli': 'tidakpeduli', 'ga perduli': 'tidakpeduli', 'orang2': 'orangorang',
        'tidak tahu': 'tidaktahu', 'gak tau': 'tidaktahu', 'ga tau': 'tidaktahu', 'gatau': 'tidaktahu', 'baik2': 'baikbaik',
        'tidak jelas': 'tidakjelas', 'gak jelas': 'tidakjelas', 'ga jelas': 'tidakjelas', 'pejabat2': 'pejabatpejabat',
        'bertanggung jawab': 'bertanggungjawab', 'bertanggung jwb': 'bertanggungjawab', 'tanggung jawab': 'tanggungjawab',
        'terima kasih': 'terimakasih', 'terima kasihh': 'terimakasih', 'amiiin': 'amin', 'manusia2': 'manusiamanusia',
        'ya allah': 'yaallah', 'ya alloh': 'yaallah', 'aamin': 'amin', 'aamiin': 'amin', 'amiin': 'amin', 'banget': 'sekali',
        'diluar': 'di luar', 'dikalimantan': 'di kalimantan', 'tiba2': 'tibatiba', 'paru paru': 'paruparu', 'paru2': 'paruparu',
        'masing2': 'masingmasing', 'bener2':'benarbenar', 'anak²': 'anakanak', 'mauu': 'mau', 'siapp': 'siap', 'biar': 'supaya',
        'hewan hewan': 'hewanhewan', 'makin': 'semakin','ya ampun': 'yaampun'
        }

    text_str = str(text)

    for phrase, replacement in phrase_dict.items():
        pattern = r'\b' + re.escape(phrase) + r'\b'
        text_str = re.sub(pattern, replacement, text_str)

    words = text_str.split()
    corrected_words = [typo_dict.get(w, w) for w in words]

    return " ".join(corrected_words)

df['6_spelling'] = df['5_normalization'].apply(correct_spelling)

print("6. Spelling Correction")
display(df['6_spelling'].head(10))

6. Spelling Correction

0    dan tidakada yang bertanggungjawab atas karhut...
1    hancur bgt hati liat hutan segundul itu emoji_...
2    cocok ditanam sawit kata mereka yang membakar ...
3    tuhan beri keajaiban utk indonesia emoji_hati_...
4    please jangan disingkat jadi karhutla kita seb...
5             emoji_wajah_babi tidak separah di medsos
6    siapa yg bilang sudah normal emoji_wajah_sanga...
7    pak ada tindakan supaya masalah ini kelar gak ...
8    pemerintah sedang mem black campaign dirinya s...
9    terimakasih sdh bersuara emoji_hati_merah emoj...
Name: 6_spelling, dtype: object

In [222]:
def convert_chat_words(text):
    slang_dict = {
        'tpi': 'tapi', 'tp': 'tapi', 'bg': 'bang', 'makasih': 'terima kasih', 'tmn': 'teman', 'tmn2': 'teman',
        'trmksh': 'terima kasih', 'terimakasih': 'terima kasih', 'trimksh':'terima kasih',
        'nanem': 'menanam', 'nggak': 'tidak', 'tidak ada': 'tidakada', 'gaada': 'tidakada',
        'nangkep': 'menangkap', 'kek': 'seperti', 'brpa': 'berapa', 'orng': 'orang', 'udah': 'sudah',
        'org': 'orang', 'aq': 'aku', 'sy': 'saya', 'emang': 'memang', 'gini': 'begini',
        'gimana': 'bagaimana', 'gmn': 'bagaimana', 'dpt': 'dapat', 'pengen': 'pengin',
        'knp': 'kenapa', 'ntah': 'entah', 'temen': 'teman', 'yg': 'yang', 'enggak': 'tidak',
        'sdh': 'sudah', 'udh': 'sudah', 'dah': 'sudah', 'utk': 'untuk', 'kayak': 'seperti',
        'gk': 'tidak', 'gak': 'tidak', 'ga': 'tidak', 'tdk': 'tidak', 'tak':'tidak','tiba2': 'tibatiba',
        'msh': 'masih', 'jd': 'jadi', 'jgn': 'jangan', 'klo': 'kalau', 'dl': 'dulu', 'gesek2': 'gesek',
        'pake': 'pakai', 'liat': 'lihat', 'sampe': 'sampai', 'smpe': 'sampai', 'tak': 'tidak',
        'dgn': 'dengan', 'plis': 'please', 'pls': 'please', 'kasian': 'kasihan', 'bgt':'banget',
        'dg': 'dengan', 'd': 'di', 'bnr': 'benar', 'bener': 'benar', 'dr': 'dari', 'sept':'september', 'sosmed': 'media sosial',
        'lg': 'lagi', 'smoga': 'semoga', 'pdhl': 'padahal', 'tar': 'sebentar', 'medsos': 'mediasosial'

        }
    return " ".join([slang_dict.get(w, w) for w in str(text).split()])

df['7_chat_words'] = df['6_spelling'].apply(convert_chat_words)

print("7. Chat Words Conversion")
display(df['7_chat_words'].head(10))

7. Chat Words Conversion

0    dan tidakada yang bertanggungjawab atas karhut...
1    hancur banget hati lihat hutan segundul itu em...
2    cocok ditanam sawit kata mereka yang membakar ...
3    tuhan beri keajaiban untuk indonesia emoji_hat...
4    please jangan disingkat jadi karhutla kita seb...
5        emoji_wajah_babi tidak separah di mediasosial
6    siapa yang bilang sudah normal emoji_wajah_san...
7    pak ada tindakan supaya masalah ini kelar tida...
8    pemerintah sedang mem black campaign dirinya s...
9    terima kasih sudah bersuara emoji_hati_merah e...
Name: 7_chat_words, dtype: object

In [223]:
import re
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stop_words = set(factory.get_stop_words())

kata_negasi = {'tidak', 'bukan', 'belum', 'jangan'}
stop_words = stop_words - kata_negasi
stop_words.update({'berada', 'mem','begini','gini', 'sedang', 'lah', 'tuh', 'yakali'
      'hiya', 'tara', 'makjrengg', 'pas', 'ku', 'nya','mu', 'si', 'kok', 'euy', 'nih', 'heh'
      'yakali', 'wahh', "nii", 'keadaan', 'mau', 'pak', 'jadi', 'seperti', 'sekali', 'cuma', 'memang',
      'buat', 'bahkan', 'terlalu', 'mudah', 'banget', 'selalu', 'sama', 'selalu', 'semua',
      'diantaranya', 'melalui', 'sana', 'sekitar', 'sebentar', 'bakal', 'kalau', 'bareng'
      })

def remove_stopwords(text):
    if not isinstance(text, str):
        return ""
    words = str(text).split()
    filtered = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered)

df['8_stopword'] = df['7_chat_words'].apply(remove_stopwords)
df['8_stopword'] = df['8_stopword'].apply(
    lambda x: re.sub(r'\s+', ' ', x).strip()
)

print('8. Removal of Stopwords')
display(df['8_stopword'].head(10))

8. Removal of Stopwords

0    tidakada bertanggungjawab atas karhutla emoji_...
1    hancur hati lihat hutan segundul emoji_patah_hati
2    cocok ditanam sawit kata membakar emoji_api em...
3      tuhan beri keajaiban indonesia emoji_hati_merah
4    please jangan disingkat karhutla sebut hutan l...
5           emoji_wajah_babi tidak separah mediasosial
6    siapa bilang normal emoji_wajah_sangat_marah e...
7    tindakan masalah kelar tidak jujur mahasiswa l...
8            pemerintah black campaign dirinya sendiri
9    terima kasih bersuara emoji_hati_merah emoji_w...
Name: 8_stopword, dtype: object

In [224]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
dictionary = factory.get_words()

custom_words = {
    'rasa', 'pemerintah', 'selimut', 'menteri', 'ingin',
    'tangis', 'puas', 'pemadam', 'anak', 'pelaku'
    }

for word in custom_words:
    dictionary.append(word)

stemmer = factory.create_stemmer()
STEM_OVERRIDE_MAP = {
    'terasa': 'rasa', 'berasa': 'rasa', 'merasa': 'rasa',
    'pemerintah': 'pemerintah',
    'selimut': 'selimut', 'diselimuti': 'selimut',
    'menteri': 'menteri', 'kementrian': 'kementrian',
    'pengen': 'ingin', 'pengin': 'ingin', 'menginginkan': 'ingin',
    'nangis': 'tangis', 'menangis': 'tangis', 'tangisan': 'tangis',
    'puas': 'puas', 'memuaskan': 'puas', 'kepuasan': 'puas',
    'pemadam': 'pemadam',
    'anak': 'anak', 'anakan': 'anak',
    'pelaku': 'pelaku',
    'paruparu': 'paruparu',
    'tibatiba': 'tibatiba',
    'wapresnya':'wapres'
    }

def stem_per_word(text):
    words = str(text).split()
    stemmed_words = []

    for word in words:
        if word.startswith('emoji_'):
            stemmed_words.append(word)
        elif word in STEM_OVERRIDE_MAP:
            stemmed_words.append(STEM_OVERRIDE_MAP[word])
        else:
            stemmed_words.append(stemmer.stem(word))

    return ' '.join(stemmed_words)

df['9_stemming'] = df['8_stopword'].apply(stem_per_word)
df.to_csv('dataset_komentar_clean.csv', index=False, encoding='utf-8-sig')

print("9. Stemming")
display(df['9_stemming'].head(10))

9. Stemming

0    tidakada bertanggungjawab atas karhutla emoji_...
1      hancur hati lihat hutan gundul emoji_patah_hati
2    cocok tanam sawit kata bakar emoji_api emoji_a...
3          tuhan beri ajaib indonesia emoji_hati_merah
4    please jangan singkat karhutla sebut hutan lah...
5             emoji_wajah_babi tidak parah mediasosial
6    siapa bilang normal emoji_wajah_sangat_marah e...
7    tindak masalah kelar tidak jujur mahasiswa lua...
8               pemerintah black campaign diri sendiri
9    terima kasih suara emoji_hati_merah emoji_waja...
Name: 9_stemming, dtype: object

In [205]:
import pandas as pd

df = pd.read_csv('dataset_komentar_clean.csv')

for i, (sebelum, sesudah) in enumerate(
    zip(df['text'], df['9_stemming']), 1
):
    txt_sebelum = str(sebelum).replace('\n', ' ')
    txt_sesudah = str(sesudah).replace('\n', ' ')

    print(f'[{i:03d}] SEBELUM : {txt_sebelum}')
    print(f'      SESUDAH : {txt_sesudah}')
    print('-' * 80)

df.to_csv('dataset_komentar_clean_banding.csv', index=False, encoding='utf-8-sig')

[001] SEBELUM : dan tidak ada yang bertanggung jawab atas karhutla ini 😢
      SESUDAH : tidakada bertanggungjawab atas karhutla emoji_wajah_menangis
--------------------------------------------------------------------------------
[002] SEBELUM : Hancur bgt hati liat hutan segundul itu💔
      SESUDAH : hancur hati lihat hutan gundul emoji_patah_hati
--------------------------------------------------------------------------------
[003] SEBELUM : Cocok ditanam SAWIT, kata mereka yang membakar 🔥🔥🔥🔥
      SESUDAH : cocok tanam sawit kata bakar emoji_api emoji_api emoji_api emoji_api
--------------------------------------------------------------------------------
[004] SEBELUM : Tuhan beri keajaiban utk Indonesia ❤️
      SESUDAH : tuhan beri ajaib indonesia emoji_hati_merah
--------------------------------------------------------------------------------
[005] SEBELUM : Please jangan disingkat jadi “karhutla”, kita sebut saja @Kebakaran Hutan dan Lahan” supaya kegentingannya lebih terasa.
      SESUDAH : please jangan singkat karhutla sebut hutan lahan genting lebih rasa
--------------------------------------------------------------------------------
[006] SEBELUM : 🐷 : “TIDAK SEPARAH DI MEDSOS”
      SESUDAH : emoji_wajah_babi tidak parah mediasosial
--------------------------------------------------------------------------------
[007] SEBELUM : Siapa yg bilang, sudah 'NORMAL'???! 😡😡
      SESUDAH : siapa bilang normal emoji_wajah_sangat_marah emoji_wajah_sangat_marah
--------------------------------------------------------------------------------
[008] SEBELUM : Pak @prabowo ada tindakan biar masalah ini kelar gak pak?  Jujur kita mahasiswa yang berada diluar negri, liat keluarga dikalimantan rasanya sakit hati pak, belum juga soal dolar yang naik, turunnya juga gak stabil/ anjlok parah.  #savekalimantan
      SESUDAH : tindak masalah kelar tidak jujur mahasiswa luar negeri lihat keluarga kalimantan rasa sakit hati belum soal dolar naik turun tidak stabil anjlok parah
--------------------------------------------------------------------------------
[009] SEBELUM : Pemerintah sedang mem-black campaign dirinya sendiri
      SESUDAH : pemerintah black campaign diri sendiri
--------------------------------------------------------------------------------
[010] SEBELUM : terimakasih sdh bersuara❤️😢
      SESUDAH : terima kasih suara emoji_hati_merah emoji_wajah_menangis
--------------------------------------------------------------------------------
[011] SEBELUM : izin kami juga di Papua terutama di Papua Barat juga masih diselimuti kabut asap yang tebal , tuhan semoga Indonesia cepat pulih kembali amin izin, izin yaaaaa 🙏🙏❤️
      SESUDAH : izin papua utama papua barat selimut kabut asap tebal tuhan moga indonesia cepat pulih amin izin izin emoji_melipat_tangan emoji_melipat_tangan emoji_hati_merah
--------------------------------------------------------------------------------
[012] SEBELUM : 😭😭😭😭😭😭😭😭😭 diberikan amanah malah menghancurkan... Dosa lah mereka yang tidak bertanggung-jawab.. Apa yang ditabur akan segera dituai
      SESUDAH : emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras beri amanah malah hancur dosa tidak bertanggungjawab apa tabur segera tuai
--------------------------------------------------------------------------------
[013] SEBELUM : Banggg makasih bangettt udah mauu jadi pelopor buat nanem pohon di kalimantan 😭😭
      SESUDAH : bang terima kasih pelopor tanam pohon kalimantan emoji_wajah_menangis_keras emoji_wajah_menangis_keras
--------------------------------------------------------------------------------
[014] SEBELUM : Luas bnget hamparanny apakah itu nanti akan ada tanaman suwit yg tersusun rapih😢
      SESUDAH : luas hampar tanam sawit susun rapi emoji_wajah_menangis
--------------------------------------------------------------------------------
[015] SEBELUM : Hari ini tepat 2 bulan, kami warga kalimantan tengah menghirup udara asap karhutla🥹😭 entah sampai kapan keadaan kek gini 💔
      SESUDAH : hari tepat 2 bulan warga kalimantan tengah hirup udara asap karhutla emoji_wajah_menahan_air_mata emoji_wajah_menangis_keras entah kapan emoji_patah_hati
--------------------------------------------------------------------------------
[016] SEBELUM : we arent mad enough💔
      SESUDAH : we arent mad enough emoji_patah_hati
--------------------------------------------------------------------------------
[017] SEBELUM : Terimakasih sudah berusaha..tpi berkaca dari Aceh sepertinya tak terlihat dimata para penguasa
      SESUDAH : terima kasih usaha kaca aceh seperti tidak lihat mata kuasa
--------------------------------------------------------------------------------
[018] SEBELUM : Berapa hektar sudah dibakar?😢😭
      SESUDAH : berapa hektar bakar emoji_wajah_menangis emoji_wajah_menangis_keras
--------------------------------------------------------------------------------
[019] SEBELUM : jangan sampe jadi lahan sawit 😭😭💔
      SESUDAH : jangan lahan sawit emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_patah_hati
--------------------------------------------------------------------------------
[020] SEBELUM : 💔💔💔
      SESUDAH : emoji_patah_hati emoji_patah_hati emoji_patah_hati
--------------------------------------------------------------------------------
[021] SEBELUM : 💔💔💔😭😭😭
      SESUDAH : emoji_patah_hati emoji_patah_hati emoji_patah_hati emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras
--------------------------------------------------------------------------------
[022] SEBELUM : Luas banget yang hancur 😢
      SESUDAH : luas hancur emoji_wajah_menangis
--------------------------------------------------------------------------------
[023] SEBELUM : 💔💔💔
      SESUDAH : emoji_patah_hati emoji_patah_hati emoji_patah_hati
--------------------------------------------------------------------------------
[024] SEBELUM : YaAllah luas sekali 🥹
      SESUDAH : yaallah luas emoji_wajah_menahan_air_mata
--------------------------------------------------------------------------------
[025] SEBELUM : Ini tuh terlalu mudah nangkep tersangkanya, cuma ya emang gak mau aja, orang temen sendiri 😂
      SESUDAH : tangkap sangka tidakmau orang teman sendiri emoji_wajah_gembira_berurai_air_mata
--------------------------------------------------------------------------------
[026] SEBELUM : It hurts 💔
      SESUDAH : it hurts emoji_patah_hati
--------------------------------------------------------------------------------
[027] SEBELUM : Sehat buat bg jeremy, trmksh banyak bantuanya yang bahkan presiden dan mentri kehutanan pun tidak perduli
      SESUDAH : sehat bang jeremy terima kasih banyak bantu presiden menteri hutan tidak peduli
--------------------------------------------------------------------------------
[028] SEBELUM : Yakali api bisa muncul sendiri, kalau api bisa muncul sendiri manusia2 purba ga akan gesek2 kayu kering dan gesek2 batu buat bikin api…
      SESUDAH : yakali api muncul sendiri kalau api muncul sendiri manusiamanusia purba tidak gesek kayu kering gesek batu bikin api
--------------------------------------------------------------------------------
[029] SEBELUM : Sedihhh eee ya Tuhannnn😭😭😭💔💔💔💔💔
      SESUDAH : sedih e tuhan emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_patah_hati emoji_patah_hati emoji_patah_hati emoji_patah_hati emoji_patah_hati
--------------------------------------------------------------------------------
[030] SEBELUM : Suamiku mantan penduduk Kalimantan, setiap tahun selalu mengalami asap tebal dan penanganan yang sulit karena kondisi tanah gambutnya. Semoga ada solusi terbaik buat Karhutla ini, agar alam pulih kembali 💔
      SESUDAH : suami mantan duduk kalimantan tahun alami asap tebal tangan sulit kondisi tanah gambut moga solusi baik karhutla alam pulih emoji_patah_hati
--------------------------------------------------------------------------------
[031] SEBELUM : dan mereka bilang itu normal wen🥺🥺🥺🥺😭😭😭😭
      SESUDAH : bilang normal wen emoji_wajah_memelas emoji_wajah_memelas emoji_wajah_memelas emoji_wajah_memelas emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras
--------------------------------------------------------------------------------
[032] SEBELUM : Bayangkan pada gimana kemana dan seperti apa kondisi hewan hewan yg dl nya pada tinggal di situ 😢 ya allah
      SESUDAH : bayang bagaimana apa kondisi hewanhewan dulu tinggal situ emoji_wajah_menangis yaallah
--------------------------------------------------------------------------------
[033] SEBELUM : gaada aman amannya kak, aku di banjarmasin tiap hari apalagi pagi sama tengah malam, asapnya masih parah, aku pas posisi lagi sakit flu pilek, 3 masker pun masih keciuman saking parah bau asapnya, mana bikin mata perih dijalan🫠
      SESUDAH : tidakada aman aman kak aku banjarmasin tiap hari pagi tengah malam asap parah aku posisi sakit flu pilek 3 masker cium saking parah bau asap mana bikin mata perih jalan emoji_wajah_meleleh
--------------------------------------------------------------------------------
[034] SEBELUM : Tinggal nunggu waktu, beberapa saat lagi bibit-bibit sawit akan bermunculan
      SESUDAH : tinggal nunggu waktu beberapa bibit bibit sawit muncul
--------------------------------------------------------------------------------
[035] SEBELUM : separah ini😭💔
      SESUDAH : parah emoji_wajah_menangis_keras emoji_patah_hati
--------------------------------------------------------------------------------
[036] SEBELUM : Udah bukan hutan…. 😭
      SESUDAH : bukan hutan emoji_wajah_menangis_keras
--------------------------------------------------------------------------------
[037] SEBELUM : Masalahnya amannya itu gak ada yang bisa di bakar lagi😭
      SESUDAH : masalah aman tidakada bakar emoji_wajah_menangis_keras
--------------------------------------------------------------------------------
[038] SEBELUM : Yng di pecat menku🥺😭
      SESUDAH : pecat menku emoji_wajah_memelas emoji_wajah_menangis_keras
--------------------------------------------------------------------------------
[039] SEBELUM : Itu tinggal ditanam palm tree untung banyak pasti kan juragan @budidefrianto13  dalihnya pemulihan lahan "hiyaaaa"
      SESUDAH : tinggal tanam palm tree untung banyak kan juragan dalih pulih lahan hiya
--------------------------------------------------------------------------------
[040] SEBELUM : Kirim ke maudy tolong.
      SESUDAH : kirim maudy
--------------------------------------------------------------------------------
[041] SEBELUM : Cepat Pulih Kalimantan 😢😢😢💔💔
      SESUDAH : cepat pulih kalimantan emoji_wajah_menangis emoji_wajah_menangis emoji_wajah_menangis emoji_patah_hati emoji_patah_hati
--------------------------------------------------------------------------------
[042] SEBELUM : Mari kita posting ulang, dan posting Ig story agar yang lain mengetahui bahwa Kalimantan sedang tidak baik2 saja..🥺
      SESUDAH : posting ulang posting ig story tahu kalimantan tidak baikbaik emoji_wajah_memelas
--------------------------------------------------------------------------------
[043] SEBELUM : dan ini tu terjadi di seluruh kalimantan, sekali lagi di seluruh Kalimantan 🫠
      SESUDAH : jadi seluruh kalimantan seluruh kalimantan emoji_wajah_meleleh
--------------------------------------------------------------------------------
[044] SEBELUM : 😭😭😭😭
      SESUDAH : emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras
--------------------------------------------------------------------------------
[045] SEBELUM : Thankyou owen @jerhemynemo
      SESUDAH : thankyou owen
--------------------------------------------------------------------------------
[046] SEBELUM : ASTAGFIRULLAH 🥺💔
      SESUDAH : astagfirullah emoji_wajah_memelas emoji_patah_hati
--------------------------------------------------------------------------------
[047] SEBELUM : 😭😭💔💔
      SESUDAH : emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_patah_hati emoji_patah_hati
--------------------------------------------------------------------------------
[048] SEBELUM : 💔😭😟
      SESUDAH : emoji_patah_hati emoji_wajah_menangis_keras emoji_wajah_cemas
--------------------------------------------------------------------------------
[049] SEBELUM : Ya Allah habiss🥺
      SESUDAH : yaallah habiss emoji_wajah_memelas
--------------------------------------------------------------------------------
[050] SEBELUM : Pemerintah emang pengen ngilangin hutan tropis di kalimantan kayaknya
      SESUDAH : pemerintah ingin ngilangin hutan tropis kalimantan kayak
--------------------------------------------------------------------------------
[051] SEBELUM : 😢
      SESUDAH : emoji_wajah_menangis
--------------------------------------------------------------------------------
[052] SEBELUM : Di Batam saja kami sudah merasakan sesaknya asap. Tak terbayang bagaimana saudara-saudara kita di Kalimantan yang harus bertahan dan berjibaku di tengah pekatnya asap. 😢 Hasbunallahu wa ni'mal wakil. Ya Allah, jaga mereka, lindungi paru-paru dan kesehatan mereka, kuatkan hati mereka, dan segera turunkan pertolongan-Mu. Angkatlah asap dan musibah ini, gantikan dengan udara yang bersih dan keselamatan. 🤲🏻 Aamiin ya Rabbal ‘alamin.
      SESUDAH : batam rasa sesak asap tidak bayang bagaimana saudara saudara kalimantan tahan jibaku tengah pekat asap emoji_wajah_menangis hasbunallahu wa ni mal wakil yaallah jaga lindung paruparu sehat kuat hati segera turun tolong angkat asap musibah ganti udara bersih selamat emoji_tangan_diangkat_dan_dirapatkan_bersama_warna_kulit_cerah amin rabbal alamin
--------------------------------------------------------------------------------
[053] SEBELUM : Ini mau tag siapa biar orang luar tuntut pemerintah Indonesia? @unesco
      SESUDAH : tag siapa orang luar tuntut pemerintah indonesia
--------------------------------------------------------------------------------
[054] SEBELUM : Bayangin, sepedih apa azabnya pemimpin negara nanti
      SESUDAH : bayangin pedih apa azab pimpin negara
--------------------------------------------------------------------------------
[055] SEBELUM : 😢🥺
      SESUDAH : emoji_wajah_menangis emoji_wajah_memelas
--------------------------------------------------------------------------------
[056] SEBELUM : Kawal terus, apakah ini bakal jadi LAHAN SAWIT ??? PANTAU TERUS.
      SESUDAH : kawal terus bakal lahan sawit pantau terus
--------------------------------------------------------------------------------
[057] SEBELUM : 😭😭😭😭😭😭… butuh berapa tahun untuk menghijaukan kembali …😢😢😢😢😢😢
      SESUDAH : emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_wajah_menangis_keras butuh berapa tahun hijau emoji_wajah_menangis emoji_wajah_menangis emoji_wajah_menangis emoji_wajah_menangis emoji_wajah_menangis emoji_wajah_menangis
--------------------------------------------------------------------------------
[058] SEBELUM : Nangis kita semua. 💔💔
      SESUDAH : tangis emoji_patah_hati emoji_patah_hati
--------------------------------------------------------------------------------
[059] SEBELUM : masing2 ambil 1 hektar ya buat kalian jangn rebutan
      SESUDAH : masingmasing ambil 1 hektar kalian jangan rebut
--------------------------------------------------------------------------------
[060] SEBELUM : Palembang makin parah bang💔
      SESUDAH : palembang makin parah bang emoji_patah_hati
--------------------------------------------------------------------------------
[061] SEBELUM : 💔💔💔
      SESUDAH : emoji_patah_hati emoji_patah_hati emoji_patah_hati
--------------------------------------------------------------------------------
[062] SEBELUM : Dpt kabar temen di ponti sudah bisa lihat langit setelah 2 bulan, ternyata tmn2 di palangka masih berjuang 🥺 yg jauh, ubah energi sedihmu jadi bantuan utk para pahlawan relawan karhutla diantaranya melalui @ddkalteng .
      SESUDAH : kabar teman ponti lihat langit 2 bulan nyata teman palangka juang emoji_wajah_memelas jauh ubah energi sedih bantu pahlawan rawan karhutla
--------------------------------------------------------------------------------
[063] SEBELUM : 😭😭💔💔
      SESUDAH : emoji_wajah_menangis_keras emoji_wajah_menangis_keras emoji_patah_hati emoji_patah_hati
--------------------------------------------------------------------------------
[064] SEBELUM : 😢😢😢😢
      SESUDAH : emoji_wajah_menangis emoji_wajah_menangis emoji_wajah_menangis emoji_wajah_menangis
--------------------------------------------------------------------------------
[065] SEBELUM : Jujur emosi💔😭
      SESUDAH : jujur emosi emoji_patah_hati emoji_wajah_menangis_keras
--------------------------------------------------------------------------------
[066] SEBELUM : Terima kasih sudah membantu dan menyuarakan kami di Kalimantan 😔🤍
      SESUDAH : terima kasih bantu suara kalimantan emoji_wajah_merenung emoji_hati_putih
--------------------------------------------------------------------------------
[067] SEBELUM : 😢🥺
      SESUDAH : emoji_wajah_menangis emoji_wajah_memelas
--------------------------------------------------------------------------------
[068] SEBELUM : Beberapa bulan atau tahun ke depan dipantau lagi apakah ditanam sawit atau masih tumbuh hutan. Sebagai pembuktian ini kebakaran sengaja atau enggak
      SESUDAH : beberapa bulan tahun depan pantau tanam sawit tumbuh hutan bukti bakar sengaja tidak
--------------------------------------------------------------------------------
[069] SEBELUM : Sebagai org kalimantan, saya no comment untuk masalah udara yg kita pasti nya hirup di sluruh borneo ini, setiap ulasan kita lontarkan keseluruh jagat sosmed , tp semua meanggap itu hanya biasa saja , jd mungkin Kemanusiaan dimuka bumi ini udh tak ada harga nya untuk 1 nyawa yg hilang dari 1 detik hembusan nafasnya, kurangnya, penanganan, bantuan, dan janji pemimpin yang mengayomi dan mensejahterakan rakyatnya justru sebaliknya, jadi siapa lagi kalo bukan kita yg bergerak bersama demi membuka langit biru yang cerah, biarkanlah orang tak percaya bagaimana penderitaan disni, nanti juga mereka merasakan dampak dari hilangnya hutan yng menjadi paru2nya dunia. 🥺
      SESUDAH : orang kalimantan no comment masalah udara hirup seluruh borneo ulas lontar seluruh jagat media sosial meanggap biasa mungkin manusia muka bumi tidak harga 1 nyawa hilang 1 detik hembus nafas kurang tangan bantu janji pimpin ayom sejahtera rakyat justru balik siapa kalo bukan gerak sama buka langit biru cerah biar orang tidak percaya bagaimana derita sini rasa dampak hilang hutan jadi paru2nya dunia emoji_wajah_memelas
--------------------------------------------------------------------------------
[070] SEBELUM : Sedih banget liatnya 🥺
      SESUDAH : sedih liat emoji_wajah_memelas
--------------------------------------------------------------------------------
[071] SEBELUM : 💔💔😢😢
      SESUDAH : emoji_patah_hati emoji_patah_hati emoji_wajah_menangis emoji_wajah_menangis
--------------------------------------------------------------------------------
[072] SEBELUM : Ironisnya ada iklan di tv yg bangga pemerintah memperluas persawitannya, katanya warisan indonesia akan kembali dg adanya hutan sawit 😂😂
      SESUDAH : ironis iklan tv bangga pemerintah luas sawit kata waris indonesia ada hutan sawit emoji_wajah_gembira_berurai_air_mata emoji_wajah_gembira_berurai_air_mata
--------------------------------------------------------------------------------
[073] SEBELUM : Nanti juga tumbuh lagi... Jadi Sawit 😂
      SESUDAH : tumbuh sawit emoji_wajah_gembira_berurai_air_mata